title: rainmaker
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Arduino UNO based controller using BME280 environmental sensor.
baseurl: "/rainmaker" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  jarjuk

# Build settings
# markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
